name: template
description: This one just test template.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  dio: ^4.0.4
  shared_preferences: ^2.0.11
  path_provider: ^2.0.10
  firebase_auth: ^3.3.3
  firebase_messaging: 13.0.0
  cloud_firestore: ^3.1.4
  firebase_storage: ^10.2.3
  flutter_local_notifications: #^9.1.5
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.5.3+2
  get: ^4.6.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  assets:
    - assets/images/

  uses-material-design: true
  fonts:
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.otf
        - asset: assets/fonts/WorkSans-SemiBold.otf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.otf
          weight: 800
